# Generated by Django 4.0 on 2022-01-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=200)),
                ('bdate', models.DateTimeField()),
                ('btext', models.TextField(max_length=500)),
                ('bautor', models.CharField(max_length=50)),
            ],
        ),
    ]
