# Generated by Django 4.0 on 2022-01-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='bdate',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
