# Generated by Django 4.0 on 2022-01-06 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_options_alter_blogs_bdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 9, 6, 13, 450693, tzinfo=utc)),
        ),
    ]
