# Generated by Django 4.0 on 2022-01-06 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blogs', '0004_alter_blogs_bdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='bautor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='author_id'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 10, 49, 27, 672819, tzinfo=utc)),
        ),
    ]
