# Generated by Django 4.0 on 2022-01-06 12:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogs_bautor_alter_blogs_bdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 12, 52, 6, 509430, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='blogs',
            name='comment',
            field=models.ManyToManyField(to='blogs.comment'),
        ),
    ]
