# Generated by Django 4.0 on 2022-01-07 13:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blogs', '0006_comment_alter_blogs_bdate_blogs_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='bautor',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.blogs'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 13, 0, 51, 952062, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='btext',
            field=models.TextField(default=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='btitle',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.author'),
        ),
    ]
