# Generated by Django 4.0 on 2022-01-07 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_blogs_bautor_remove_blogs_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 13, 4, 10, 246301, tzinfo=utc)),
        ),
    ]
