# Generated by Django 3.2.4 on 2022-01-09 08:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blogs_bdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 8, 14, 37, 240043, tzinfo=utc)),
        ),
    ]
