# Generated by Django 4.0 on 2022-01-10 08:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_blogs_bdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-cdate']},
        ),
        migrations.AddField(
            model_name='comment',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 8, 48, 30, 505664, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 8, 48, 30, 504993, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogs'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(max_length=500),
        ),
    ]
