# Generated by Django 4.0 on 2022-01-10 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_comment_options_comment_cdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 8, 51, 54, 759974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 8, 51, 54, 760624, tzinfo=utc)),
        ),
    ]
