# Generated by Django 4.0 on 2022-01-10 13:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_blogs_bdate_alter_comment_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 13, 20, 19, 28565, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 13, 20, 19, 29889, tzinfo=utc)),
        ),
    ]
